
# Generated by Django 3.1.3 on 2020-11-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.CharField(choices=[(1, 'Osteopathy'), (2, 'Dentistry'), (3, 'Ophthalmology'), (4, 'Dermatology')], max_length=100, verbose_name='Department'),
        ),
    ]